In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
#List of list can be said as a numpy array
b = np.array(my_matrix)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
b.shape


(3, 3)

In [6]:
type(b)

numpy.ndarray

In [7]:
m = np.asmatrix(b)
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
type(m)

numpy.matrix

In [9]:
m.ndim

2

In [10]:
z = np.array([0,1,2],ndmin=5)
z

array([[[[[0, 1, 2]]]]])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.arange(0, 5, 0.5,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.linspace(0,12,2)

array([ 0., 12.])

In [21]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [22]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [23]:
np.random.rand(2)

array([0.73164418, 0.61948849])

In [24]:
import numpy as np
import matplotlib.pyplot as plt

sample_size = 100000
uniform = np.random.rand(sample_size)
normal = np.random.randn(sample_size)

pdf, bins, patches = plt.hist(uniform, bins=20, range=(0, 1), density=True)
plt.title('rand: uniform')
plt.show()

pdf, bins, patches = plt.hist(normal, bins=20, range=(-4, 4), density=True)
plt.title('randn: normal')
plt.show()

ModuleNotFoundError: No module named 'PIL'

In [25]:
np.random.randint(1,100,10)

array([13, 98, 18, 70, 29, 18, 75, 97, 87, 26])

In [26]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,5,1,-1).shape

(5, 5, 1, 1)

In [29]:
ranarr = np.random.randint(0,50,10)
ranarr

array([17,  7,  4, 16,  2,  1, 42, 15,  0,  6])

In [30]:
ranarr.max()

42

In [31]:
ranarr.min()

0

In [32]:
ranarr.argmax()

6

In [33]:
ranarr.argmin()

8

In [34]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.dtype

dtype('int32')

In [36]:
type(arr)

numpy.ndarray

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr[8]

8

In [39]:
# 2D array slicing
arr_2d =arr.reshape(5,5)
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [40]:
#Shape bottom row
arr_2d[2,:]

array([10, 11, 12, 13, 14])

In [41]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [42]:
arr[arr>40]

array([], dtype=int32)

In [43]:
arr[arr<40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [46]:
arr /arr

C:\Users\rosha\AppData\Local\Temp\ipykernel_14156\591710190.py:1: RuntimeWarning: invalid value encountered in divide
  arr /arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [49]:
arr[0]=0

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [52]:
np.argmax(arr)

24

In [53]:
np.max(arr)

24

In [54]:
max(arr)

24

In [55]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [57]:
mat.sum()

325

In [58]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [59]:
#np.dot()
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [60]:
x+v

array([[10, 12],
       [12, 14]])

In [61]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(v@w)
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

219
219
219
[29 67]
[29 67]


In [62]:

print(v*w)
print(np.multiply(v, w))

print(v.T)

[ 99 120]
[ 99 120]
[ 9 10]
