In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [4]:
#List of list can be said as a numpy array
b = np.array(my_matrix)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
